//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("amp.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About - {0}|About as in about.
        /// </summary>
        public static string msgAboutTitle {
            get {
                return ResourceManager.GetString("msgAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding songs: {0} / {1}...|A conditional database add is in progress..
        /// </summary>
        public static string msgAddDB {
            get {
                return ResourceManager.GetString("msgAddDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding songs to album: {0} / {1}...|A conditional database album add is in progress..
        /// </summary>
        public static string msgAddDBAlbum {
            get {
                return ResourceManager.GetString("msgAddDBAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album|As in a name of an album of a music file.
        /// </summary>
        public static string msgAlbum {
            get {
                return ResourceManager.GetString("msgAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate queue index|As an alternate queue index of a music file.
        /// </summary>
        public static string msgAlternateQueue {
            get {
                return ResourceManager.GetString("msgAlternateQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Artist|As in an artist(s) of a music file.
        /// </summary>
        public static string msgArtists {
            get {
                return ResourceManager.GetString("msgArtists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm|Used in a dialog title to ask for a confirmation to do something.
        /// </summary>
        public static string msgConfirmation {
            get {
                return ResourceManager.GetString("msgConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default|Default as in default album.
        /// </summary>
        public static string msgDefault {
            get {
                return ResourceManager.GetString("msgDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error|A common error that should be defined in another message.
        /// </summary>
        public static string msgError {
            get {
                return ResourceManager.GetString("msgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A script error occurred on the database update|Something failed during running the database update script.
        /// </summary>
        public static string msgErrorInScript {
            get {
                return ResourceManager.GetString("msgErrorInScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export queue to file|As in export a queue snapshot to a file.
        /// </summary>
        public static string msgExportQueueTo {
            get {
                return ResourceManager.GetString("msgExportQueueTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to amp# queue export files (*.amp#_qex)|*.amp#_qex|as in the combo box to select file type from a dialog.
        /// </summary>
        public static string msgFileExt_amp_qex {
            get {
                return ResourceManager.GetString("msgFileExt_amp_qex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M3U playlist files (*.m3u;*.m3u8)|*.m3u;*.m3u8|as in the combo box to select file type from a dialog.
        /// </summary>
        public static string msgFileExt_m3u {
            get {
                return ResourceManager.GetString("msgFileExt_m3u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifying songs: {0} / {1}...|Songs are identified based on the database song data..
        /// </summary>
        public static string msgIDSong {
            get {
                return ResourceManager.GetString("msgIDSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import queue from file|As in import a queue snapshot from a file.
        /// </summary>
        public static string msgImportQueueFrom {
            get {
                return ResourceManager.GetString("msgImportQueueFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information|Some information is given to the user, do add more definitive message to make some sense to the &apos;information&apos;....
        /// </summary>
        public static string msgInformation {
            get {
                return ResourceManager.GetString("msgInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In queue: {0}|How many songs ar in the queue.
        /// </summary>
        public static string msgInQueue {
            get {
                return ResourceManager.GetString("msgInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading album &apos;{0}&apos;...|Text for loading an album (enumerating files and their tags).
        /// </summary>
        public static string msgLoadingAlbum {
            get {
                return ResourceManager.GetString("msgLoadingAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata loading: {0} / {1}...|Song metadata(tags) is being loaded..
        /// </summary>
        public static string msgLoadMeta {
            get {
                return ResourceManager.GetString("msgLoadMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify saved queue [{0}]|A text to display in the window title where a saved queue is being modified.
        /// </summary>
        public static string msgModifyQueueCaption {
            get {
                return ResourceManager.GetString("msgModifyQueueCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I named this song my self|The user has renamed the song him self.
        /// </summary>
        public static string msgMusicFileRenamed {
            get {
                return ResourceManager.GetString("msgMusicFileRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open playlist file|As in open a play list file (m3u).
        /// </summary>
        public static string msgOpenPlaylistFile {
            get {
                return ResourceManager.GetString("msgOpenPlaylistFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause|Pause playback.
        /// </summary>
        public static string msgPause {
            get {
                return ResourceManager.GetString("msgPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play|Play a song or resume paused.
        /// </summary>
        public static string msgPlay {
            get {
                return ResourceManager.GetString("msgPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing files...|A message describing a possible lenghty operation with files is running..
        /// </summary>
        public static string msgProcessingFiles {
            get {
                return ResourceManager.GetString("msgProcessingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress: {0} %|A message describing some operation progress in percentage..
        /// </summary>
        public static string msgProgressPercentage {
            get {
                return ResourceManager.GetString("msgProgressPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert non-MP3 files to MP3 format?|A query to ask whether to convert files other than MP3 to MP3 format..
        /// </summary>
        public static string msgQueryConvertToMP3 {
            get {
                return ResourceManager.GetString("msgQueryConvertToMP3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really delete album named: &apos;{0}&apos;?|A confirmation query for the user that a deletion of an album is intended..
        /// </summary>
        public static string msgQueryDeleteAlbum {
            get {
                return ResourceManager.GetString("msgQueryDeleteAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version is available to download. Download now?|A message describing that a new version of the software is available to download and the user is asked whether to download it now..
        /// </summary>
        public static string msgQueryDownloadNewVersion {
            get {
                return ResourceManager.GetString("msgQueryDownloadNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version is available|A dialog title informing a user of a new version download possibility.
        /// </summary>
        public static string msgQueryNewVersionTitle {
            get {
                return ResourceManager.GetString("msgQueryNewVersionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue|As in a queue snapshot.
        /// </summary>
        public static string msgQueue {
            get {
                return ResourceManager.GetString("msgQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy songs into a single directory|A title to a folder select dialog indicating that files in a queue should be copied into a single directory..
        /// </summary>
        public static string msgQueueCopyFlat {
            get {
                return ResourceManager.GetString("msgQueueCopyFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add some songs to the queue.|Ask in nicely ask the user to queue some songs..
        /// </summary>
        public static string msgQueueSomething {
            get {
                return ResourceManager.GetString("msgQueueSomething", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue index|As a queue index of a music file.
        /// </summary>
        public static string msgQueueTag {
            get {
                return ResourceManager.GetString("msgQueueTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Quiet hours ({0} - {1})]|As in quiet hours defined in the settings are occurring now :-(.
        /// </summary>
        public static string msgQuietHours {
            get {
                return ResourceManager.GetString("msgQuietHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading tags {0}...|The program is reading tag information from music files.
        /// </summary>
        public static string msgReadingTags {
            get {
                return ResourceManager.GetString("msgReadingTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote control HTTP binding failed to initialize ({0}) with an exception {1}.|As in the WCF self-hosting web service failed to initialize..
        /// </summary>
        public static string msgRemoteWCFFailed {
            get {
                return ResourceManager.GetString("msgRemoteWCFFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove queue snapshot {0}?|A confirmation question if a queue snapshot can be removed when asked from the user.
        /// </summary>
        public static string msgRemoveQueueSnapshot {
            get {
                return ResourceManager.GetString("msgRemoveQueueSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save playlist file|As in export an album to a playlist file (m3u).
        /// </summary>
        public static string msgSavePlaylistFile {
            get {
                return ResourceManager.GetString("msgSavePlaylistFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title|As in a title of a music file.
        /// </summary>
        public static string msgTitle {
            get {
                return ResourceManager.GetString("msgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current album is temporary album.{0}Please create an album with a name before continuing.|Album is a temporary one i.e. you clicked a music file and the program started. Can&apos;t save a anything against a temporary album..
        /// </summary>
        public static string msgTmpAlbumError {
            get {
                return ResourceManager.GetString("msgTmpAlbumError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track number|As a track number of a song in a music album.
        /// </summary>
        public static string msgTrackNO {
            get {
                return ResourceManager.GetString("msgTrackNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file extension.|The file extension is not in the list of supported file types..
        /// </summary>
        public static string msgUnsupportedExt {
            get {
                return ResourceManager.GetString("msgUnsupportedExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating song list: {0} / {1}...|A conditional database update is in progress..
        /// </summary>
        public static string msgUpdateDB {
            get {
                return ResourceManager.GetString("msgUpdateDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while exporting the user data.|Something failed during compressing the user data to a ZIP file.
        /// </summary>
        public static string msgUserDataExportError {
            get {
                return ResourceManager.GetString("msgUserDataExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}|As in version.
        /// </summary>
        public static string msgVersionText {
            get {
                return ResourceManager.GetString("msgVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working...|The program is loading something.
        /// </summary>
        public static string msgWorking {
            get {
                return ResourceManager.GetString("msgWorking", resourceCulture);
            }
        }
    }
}
