//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amp.Shared.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ColorsDescriptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ColorsDescriptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("amp.Shared.Localization.ColorsDescriptions", typeof(ColorsDescriptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button image default color.
        /// </summary>
        public static string ButtonImageDefaultColor {
            get {
                return ResourceManager.GetString("ButtonImageDefaultColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear search button image color.
        /// </summary>
        public static string ClearSearchButtonColor {
            get {
                return ResourceManager.GetString("ClearSearchButtonColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left audio level bar background color.
        /// </summary>
        public static string ColorLevelBarLeftBackground {
            get {
                return ResourceManager.GetString("ColorLevelBarLeftBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left audio level bar end color.
        /// </summary>
        public static string ColorLevelBarLeftEnd {
            get {
                return ResourceManager.GetString("ColorLevelBarLeftEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left audio level bar start color.
        /// </summary>
        public static string ColorLevelBarLeftStart {
            get {
                return ResourceManager.GetString("ColorLevelBarLeftStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right audio level bar background color.
        /// </summary>
        public static string ColorLevelBarRightBackground {
            get {
                return ResourceManager.GetString("ColorLevelBarRightBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right audio level bar end color.
        /// </summary>
        public static string ColorLevelBarRightEnd {
            get {
                return ResourceManager.GetString("ColorLevelBarRightEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right audio level bar start color.
        /// </summary>
        public static string ColorLevelBarRightStart {
            get {
                return ResourceManager.GetString("ColorLevelBarRightStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main volume slider image color.
        /// </summary>
        public static string ColorMainVolumeSlider {
            get {
                return ResourceManager.GetString("ColorMainVolumeSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main volume value indicator color.
        /// </summary>
        public static string ColorMainVolumeValueIndicator {
            get {
                return ResourceManager.GetString("ColorMainVolumeValueIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position slider image color.
        /// </summary>
        public static string ColorPositionSlider {
            get {
                return ResourceManager.GetString("ColorPositionSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position slider value indicator color.
        /// </summary>
        public static string ColorPositionSliderValueIndicator {
            get {
                return ResourceManager.GetString("ColorPositionSliderValueIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating slider image color.
        /// </summary>
        public static string ColorRatingSlider {
            get {
                return ResourceManager.GetString("ColorRatingSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating slider value indicator color.
        /// </summary>
        public static string ColorRatingSliderValueIndicator {
            get {
                return ResourceManager.GetString("ColorRatingSliderValueIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main volume slider speaker image color.
        /// </summary>
        public static string ColorSpeakerMainVolume {
            get {
                return ResourceManager.GetString("ColorSpeakerMainVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track volume slider speaker image color.
        /// </summary>
        public static string ColorSpeakerTrackVolume {
            get {
                return ResourceManager.GetString("ColorSpeakerTrackVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrum visualizer background color.
        /// </summary>
        public static string ColorSpectrumVisualizerBackground {
            get {
                return ResourceManager.GetString("ColorSpectrumVisualizerBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool button image default color.
        /// </summary>
        public static string ColorToolButtonImage {
            get {
                return ResourceManager.GetString("ColorToolButtonImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color for an image indicating a missing track image.
        /// </summary>
        public static string ColorTrackMissingImage {
            get {
                return ResourceManager.GetString("ColorTrackMissingImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track volume slider image color.
        /// </summary>
        public static string ColorTrackVolumeSlider {
            get {
                return ResourceManager.GetString("ColorTrackVolumeSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track volume value indicator color.
        /// </summary>
        public static string ColorTrackVolumeValueIndicator {
            get {
                return ResourceManager.GetString("ColorTrackVolumeValueIndicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled button image color.
        /// </summary>
        public static string DisabledButtonImageColor {
            get {
                return ResourceManager.GetString("DisabledButtonImageColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu item image alternate color.
        /// </summary>
        public static string MenuItemImageAlternateColor {
            get {
                return ResourceManager.GetString("MenuItemImageAlternateColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu item image color.
        /// </summary>
        public static string MenuItemImageColor {
            get {
                return ResourceManager.GetString("MenuItemImageColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next button image color.
        /// </summary>
        public static string NextButtonColor {
            get {
                return ResourceManager.GetString("NextButtonColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play button pause image color.
        /// </summary>
        public static string PlayButtonPauseColor {
            get {
                return ResourceManager.GetString("PlayButtonPauseColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play button play image color.
        /// </summary>
        public static string PlayButtonPlayColor {
            get {
                return ResourceManager.GetString("PlayButtonPlayColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous button image color.
        /// </summary>
        public static string PreviousButtonColor {
            get {
                return ResourceManager.GetString("PreviousButtonColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show queue button image color.
        /// </summary>
        public static string QueueButtonColor {
            get {
                return ResourceManager.GetString("QueueButtonColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat button image color.
        /// </summary>
        public static string RepeatButtonColor {
            get {
                return ResourceManager.GetString("RepeatButtonColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle button image color.
        /// </summary>
        public static string ShuffleButtonColor {
            get {
                return ResourceManager.GetString("ShuffleButtonColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrum channel {0} end color.
        /// </summary>
        public static string SpectrumChannel0EndColor {
            get {
                return ResourceManager.GetString("SpectrumChannel0EndColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spectrum channel {0} start color.
        /// </summary>
        public static string SpectrumChannel0StartColor {
            get {
                return ResourceManager.GetString("SpectrumChannel0StartColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack queue button image color.
        /// </summary>
        public static string StackQueueButtonColor {
            get {
                return ResourceManager.GetString("StackQueueButtonColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of the music note before the album select box.
        /// </summary>
        public static string TheMusicNoteColor {
            get {
                return ResourceManager.GetString("TheMusicNoteColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows background color.
        /// </summary>
        public static string WindowBackgroundColor {
            get {
                return ResourceManager.GetString("WindowBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window text color.
        /// </summary>
        public static string WindowTextColor {
            get {
                return ResourceManager.GetString("WindowTextColor", resourceCulture);
            }
        }
    }
}
