//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amp.Shared.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mac {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mac() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("amp.Shared.Localization.Mac", typeof(Mac).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring All To Front.
        /// </summary>
        public static string BringAllToFront {
            get {
                return ResourceManager.GetString("BringAllToFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Full Screen.
        /// </summary>
        public static string EnterFullScreen {
            get {
                return ResourceManager.GetString("EnterFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide amp#.
        /// </summary>
        public static string HideAmpEtoForms {
            get {
                return ResourceManager.GetString("HideAmpEtoForms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Others.
        /// </summary>
        public static string HideOthers {
            get {
                return ResourceManager.GetString("HideOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hides all other application windows.
        /// </summary>
        public static string HidesAllOtherApplicationWindows {
            get {
                return ResourceManager.GetString("HidesAllOtherApplicationWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hides the main amp.EtoForms window.
        /// </summary>
        public static string HidesTheMainAmpEtoFormsWindow {
            get {
                return ResourceManager.GetString("HidesTheMainAmpEtoFormsWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste and Match Style.
        /// </summary>
        public static string PasteAndMatchStyle {
            get {
                return ResourceManager.GetString("PasteAndMatchStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All Windows.
        /// </summary>
        public static string ShowAllWindows {
            get {
                return ResourceManager.GetString("ShowAllWindows", resourceCulture);
            }
        }
    }
}
