//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amp.Shared.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("amp.Shared.Localization.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file name to backup the application data before complete startup..
        /// </summary>
        public static string AFileNameToBackupTheApplicationDataBeforeCompleteStartup {
            get {
                return ResourceManager.GetString("AFileNameToBackupTheApplicationDataBeforeCompleteStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album name can not be an empty string..
        /// </summary>
        public static string AlbumNameCanNotBeAnEmptyString {
            get {
                return ResourceManager.GetString("AlbumNameCanNotBeAnEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A process identifier (PID) to wait for exit before starting the application..
        /// </summary>
        public static string AProcessIdentifierPIDToWaitForExitBeforeStartingTheApplication {
            get {
                return ResourceManager.GetString("AProcessIdentifierPIDToWaitForExitBeforeStartingTheApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sequence option &apos;{0}&apos; is defined with fewer or more items than required..
        /// </summary>
        public static string ASequenceOption0IsDefinedWithFewerOrMoreItemsThanRequired {
            get {
                return ResourceManager.GetString("ASequenceOption0IsDefinedWithFewerOrMoreItemsThanRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sequence value not bound to option name is defined with few items than required..
        /// </summary>
        public static string ASequenceValueNotBoundToOptionNameIsDefinedWithFewItemsThanRequired {
            get {
                return ResourceManager.GetString("ASequenceValueNotBoundToOptionNameIsDefinedWithFewItemsThanRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value not bound to option name is defined with a bad format..
        /// </summary>
        public static string AValueNotBoundToOptionNameIsDefinedWithABadFormat {
            get {
                return ResourceManager.GetString("AValueNotBoundToOptionNameIsDefinedWithABadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup completed.
        /// </summary>
        public static string BackupCompleted {
            get {
                return ResourceManager.GetString("BackupCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup restore completed..
        /// </summary>
        public static string BackupRestoreCompleted {
            get {
                return ResourceManager.GetString("BackupRestoreCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1} tracks, {2} albums, {3} album entries and {4} queue snapshot entries will be converted..
        /// </summary>
        public static string ConversionStatistics {
            get {
                return ResourceManager.GetString("ConversionStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert database.
        /// </summary>
        public static string ConvertDatabase {
            get {
                return ResourceManager.GetString("ConvertDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display more information on a specific command..
        /// </summary>
        public static string DisplayMoreInformationOnASpecificCommand {
            get {
                return ResourceManager.GetString("DisplayMoreInformationOnASpecificCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display this help screen..
        /// </summary>
        public static string DisplayThisHelpScreen {
            get {
                return ResourceManager.GetString("DisplayThisHelpScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display version information..
        /// </summary>
        public static string DisplayVersionInformation {
            get {
                return ResourceManager.GetString("DisplayVersionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to convert the old database into the new format? The operation might take few minutes..
        /// </summary>
        public static string DoYouWantToConvertTheOldDatabaseIntoTheNewFormatTheOperationMightTakeFewMinutes {
            get {
                return ResourceManager.GetString("DoYouWantToConvertTheOldDatabaseIntoTheNewFormatTheOperationMightTakeFewMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR(S): .
        /// </summary>
        public static string ERRORS {
            get {
                return ResourceManager.GetString("ERRORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting value to option &apos;{0}&apos;: {1}.
        /// </summary>
        public static string ErrorSettingValueToOption01 {
            get {
                return ResourceManager.GetString("ErrorSettingValueToOption01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; was not found..
        /// </summary>
        public static string File0WasNotFound {
            get {
                return ResourceManager.GetString("File0WasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading {0:F1} %.
        /// </summary>
        public static string LoadingPercentage {
            get {
                return ResourceManager.GetString("LoadingPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: Backup and restore requires application restart..
        /// </summary>
        public static string NOTEBackupAndRestoreRequiresApplicationRestart {
            get {
                return ResourceManager.GetString("NOTEBackupAndRestoreRequiresApplicationRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No verb selected..
        /// </summary>
        public static string NoVerbSelected {
            get {
                return ResourceManager.GetString("NoVerbSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; has no value..
        /// </summary>
        public static string Option0HasNoValue {
            get {
                return ResourceManager.GetString("Option0HasNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; is defined multiple times..
        /// </summary>
        public static string Option0IsDefinedMultipleTimes {
            get {
                return ResourceManager.GetString("Option0IsDefinedMultipleTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; is defined with a bad format..
        /// </summary>
        public static string Option0IsDefinedWithABadFormat {
            get {
                return ResourceManager.GetString("Option0IsDefinedWithABadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options: {0} are not compatible with {1}..
        /// </summary>
        public static string Options0AreNotCompatibleWith1 {
            get {
                return ResourceManager.GetString("Options0AreNotCompatibleWith1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Override current queue stash?.
        /// </summary>
        public static string OverrideCurrentQueueStash {
            get {
                return ResourceManager.GetString("OverrideCurrentQueueStash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set the help path from the settings..
        /// </summary>
        public static string PleaseSetTheHelpPathFromTheSettings {
            get {
                return ResourceManager.GetString("PleaseSetTheHelpPathFromTheSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required option &apos;{0}&apos; is missing..
        /// </summary>
        public static string RequiredOption0IsMissing {
            get {
                return ResourceManager.GetString("RequiredOption0IsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restores a backup from a zipped file into the program application data folder overriding the existing..
        /// </summary>
        public static string RestoresABackupFromAZippedFileIntoTheProgramApplicationDataFolderOverridingTheExisting {
            get {
                return ResourceManager.GetString("RestoresABackupFromAZippedFileIntoTheProgramApplicationDataFolderOverridingTheExi" +
                        "sting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save the tag changes? This will modify the actual audio file..
        /// </summary>
        public static string SaveTheTagChangedThisWillModifyTheActualAudioFile {
            get {
                return ResourceManager.GetString("SaveTheTagChangedThisWillModifyTheActualAudioFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will now exit. Re-open the application manually..
        /// </summary>
        public static string TheApplicationWillNowExitReOpenTheApplicationManually {
            get {
                return ResourceManager.GetString("TheApplicationWillNowExitReOpenTheApplicationManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will shut down after the backup has been restored. Start the software again manually..
        /// </summary>
        public static string TheApplicationWillShutDownAfterTheBackupHasBeenRestoredStartTheSoftwareAgainManually {
            get {
                return ResourceManager.GetString("TheApplicationWillShutDownAfterTheBackupHasBeenRestoredStartTheSoftwareAgainManua" +
                        "lly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default album can not be removed. Only renaming is possible..
        /// </summary>
        public static string TheDefaultAlbumCanNotBeRemovedOnlyRenamingIsPossible {
            get {
                return ResourceManager.GetString("TheDefaultAlbumCanNotBeRemovedOnlyRenamingIsPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The playback will be stopped for the backup..
        /// </summary>
        public static string ThePlaybackWillBeStoppedForTheBackup {
            get {
                return ResourceManager.GetString("ThePlaybackWillBeStoppedForTheBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token &apos;{0}&apos; is not recognized..
        /// </summary>
        public static string Token0IsNotRecognized {
            get {
                return ResourceManager.GetString("Token0IsNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        public static string Untitled {
            get {
                return ResourceManager.GetString("Untitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE:.
        /// </summary>
        public static string USAGE {
            get {
                return ResourceManager.GetString("USAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verb &apos;{0}&apos; is not recognized..
        /// </summary>
        public static string Verb0IsNotRecognized {
            get {
                return ResourceManager.GetString("Verb0IsNotRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already using the latest version of the software..
        /// </summary>
        public static string YouAreAlreadyUsingTheLatestVersionOfTheSoftware {
            get {
                return ResourceManager.GetString("YouAreAlreadyUsingTheLatestVersionOfTheSoftware", resourceCulture);
            }
        }
    }
}
