//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amp.Shared.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Settings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Settings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("amp.Shared.Localization.Settings", typeof(Settings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always use error-tolerant search.
        /// </summary>
        public static string AlwaysUseErrorTolerantSearch {
            get {
                return ResourceManager.GetString("AlwaysUseErrorTolerantSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio visualizer.
        /// </summary>
        public static string AudioVisualizer {
            get {
                return ResourceManager.GetString("AudioVisualizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio visualizer FFT Window function.
        /// </summary>
        public static string AudioVisualizerFFTWindowFunction {
            get {
                return ResourceManager.GetString("AudioVisualizerFFTWindowFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-hide album image window.
        /// </summary>
        public static string AutoHideAlbumImageWindow {
            get {
                return ResourceManager.GetString("AutoHideAlbumImageWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates upon startup.
        /// </summary>
        public static string CheckForUpdatesUponStartup {
            get {
                return ResourceManager.GetString("CheckForUpdatesUponStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string Common {
            get {
                return ResourceManager.GetString("Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease volume on quiet hours by.
        /// </summary>
        public static string DecreaseVolumeOnQuietHoursBy {
            get {
                return ResourceManager.GetString("DecreaseVolumeOnQuietHoursBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defaults.
        /// </summary>
        public static string Defaults {
            get {
                return ResourceManager.GetString("Defaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display playlist column headers.
        /// </summary>
        public static string DisplayPlaylistColumnHeaders {
            get {
                return ResourceManager.GetString("DisplayPlaylistColumnHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable quiet hours.
        /// </summary>
        public static string EnableQuietHours {
            get {
                return ResourceManager.GetString("EnableQuietHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error-tolerant search.
        /// </summary>
        public static string ErrorTolerantSearch {
            get {
                return ResourceManager.GetString("ErrorTolerantSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal level visualization.
        /// </summary>
        public static string HorizontalLevelVisualization {
            get {
                return ResourceManager.GetString("HorizontalLevelVisualization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language (requires restart).
        /// </summary>
        public static string LanguageRequiresRestart {
            get {
                return ResourceManager.GetString("LanguageRequiresRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum results.
        /// </summary>
        public static string MaximumResults {
            get {
                return ResourceManager.GetString("MaximumResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum tolerance.
        /// </summary>
        public static string MinimumTolerance {
            get {
                return ResourceManager.GetString("MinimumTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified random.
        /// </summary>
        public static string ModifiedRandom {
            get {
                return ResourceManager.GetString("ModifiedRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause on quiet hours.
        /// </summary>
        public static string PauseOnQuietHours {
            get {
                return ResourceManager.GetString("PauseOnQuietHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to percentage.
        /// </summary>
        public static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Played count.
        /// </summary>
        public static string PlayedCount {
            get {
                return ResourceManager.GetString("PlayedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string QueueActionNone {
            get {
                return ResourceManager.GetString("QueueActionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop stashed queue.
        /// </summary>
        public static string QueueActionPopStashedQueue {
            get {
                return ResourceManager.GetString("QueueActionPopStashedQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit the application.
        /// </summary>
        public static string QueueActionQuitApplication {
            get {
                return ResourceManager.GetString("QueueActionQuitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop playback.
        /// </summary>
        public static string QueueActionStopPlayback {
            get {
                return ResourceManager.GetString("QueueActionStopPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomized count.
        /// </summary>
        public static string RandomizedCount {
            get {
                return ResourceManager.GetString("RandomizedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Randomize stack from top by.
        /// </summary>
        public static string RandomizeStackFromTopBy {
            get {
                return ResourceManager.GetString("RandomizeStackFromTopBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsLower {
            get {
                return ResourceManager.GetString("SettingsLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skipped count.
        /// </summary>
        public static string SkippedCount {
            get {
                return ResourceManager.GetString("SkippedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack queue.
        /// </summary>
        public static string StackQueue {
            get {
                return ResourceManager.GetString("StackQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolerance (%).
        /// </summary>
        public static string Tolerance {
            get {
                return ResourceManager.GetString("Tolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weighted randomization enabled.
        /// </summary>
        public static string WeightedRandomizationEnabled {
            get {
                return ResourceManager.GetString("WeightedRandomizationEnabled", resourceCulture);
            }
        }
    }
}
