//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amp.Shared.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("amp.Shared.Localization.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        public static string _ {
            get {
                return ResourceManager.GetString("_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add files....
        /// </summary>
        public static string AddFiles {
            get {
                return ResourceManager.GetString("AddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add files to album....
        /// </summary>
        public static string AddFilesToAlbum {
            get {
                return ResourceManager.GetString("AddFilesToAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add folder contents....
        /// </summary>
        public static string AddFolderContents {
            get {
                return ResourceManager.GetString("AddFolderContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add folder contents to album....
        /// </summary>
        public static string AddFolderContentsToAlbum {
            get {
                return ResourceManager.GetString("AddFolderContentsToAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add music....
        /// </summary>
        public static string AddMusic {
            get {
                return ResourceManager.GetString("AddMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add music files....
        /// </summary>
        public static string AddMusicFiles {
            get {
                return ResourceManager.GetString("AddMusicFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add music to album: &apos;{0}&apos;....
        /// </summary>
        public static string AddMusicToAlbum0 {
            get {
                return ResourceManager.GetString("AddMusicToAlbum0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new album.
        /// </summary>
        public static string AddNewAlbum {
            get {
                return ResourceManager.GetString("AddNewAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album entries.
        /// </summary>
        public static string AlbumEntries {
            get {
                return ResourceManager.GetString("AlbumEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album name.
        /// </summary>
        public static string AlbumName {
            get {
                return ResourceManager.GetString("AlbumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        public static string Albums {
            get {
                return ResourceManager.GetString("Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        public static string ColonDelimiter {
            get {
                return ResourceManager.GetString("ColonDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy track files to folder....
        /// </summary>
        public static string CopyTrackFilesToFolder {
            get {
                return ResourceManager.GetString("CopyTrackFilesToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database conversion.
        /// </summary>
        public static string DatabaseConversion {
            get {
                return ResourceManager.GetString("DatabaseConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database updated.
        /// </summary>
        public static string DatabaseUpdated {
            get {
                return ResourceManager.GetString("DatabaseUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string DefaultAlbumName {
            get {
                return ResourceManager.GetString("DefaultAlbumName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete album.
        /// </summary>
        public static string DeleteAlbum {
            get {
                return ResourceManager.GetString("DeleteAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete saved queue.
        /// </summary>
        public static string DeleteSavedQueue {
            get {
                return ResourceManager.GetString("DeleteSavedQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories searched.
        /// </summary>
        public static string DirectoriesCrawled {
            get {
                return ResourceManager.GetString("DirectoriesCrawled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit the queue tracks.
        /// </summary>
        public static string EditTheQueueTracks {
            get {
                return ResourceManager.GetString("EditTheQueueTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files found.
        /// </summary>
        public static string FilesFound {
            get {
                return ResourceManager.GetString("FilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify queue.
        /// </summary>
        public static string ModifyQueue {
            get {
                return ResourceManager.GetString("ModifyQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move downwards in queue.
        /// </summary>
        public static string MoveDownwardsInQueue {
            get {
                return ResourceManager.GetString("MoveDownwardsInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move upwards in queue.
        /// </summary>
        public static string MoveUpwardsInQueue {
            get {
                return ResourceManager.GetString("MoveUpwardsInQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music files.
        /// </summary>
        public static string MusicFiles {
            get {
                return ResourceManager.GetString("MusicFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1}.
        /// </summary>
        public static string NoOfNo {
            get {
                return ResourceManager.GetString("NoOfNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Setup....
        /// </summary>
        public static string PageSetup {
            get {
                return ResourceManager.GetString("PageSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print....
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue.
        /// </summary>
        public static string Queue {
            get {
                return ResourceManager.GetString("Queue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue created.
        /// </summary>
        public static string QueueCreated {
            get {
                return ResourceManager.GetString("QueueCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue entries.
        /// </summary>
        public static string QueueEntries {
            get {
                return ResourceManager.GetString("QueueEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue name.
        /// </summary>
        public static string QueueName {
            get {
                return ResourceManager.GetString("QueueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q.
        /// </summary>
        public static string QueueShort {
            get {
                return ResourceManager.GetString("QueueShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        public static string Redo {
            get {
                return ResourceManager.GetString("Redo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry count on playback failure.
        /// </summary>
        public static string RetryCountOnPlaybackFailure {
            get {
                return ResourceManager.GetString("RetryCountOnPlaybackFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp;&amp; Close.
        /// </summary>
        public static string SaveClose {
            get {
                return ResourceManager.GetString("SaveClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current queue.
        /// </summary>
        public static string SaveCurrentQueue {
            get {
                return ResourceManager.GetString("SaveCurrentQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved queues.
        /// </summary>
        public static string SavedQueues {
            get {
                return ResourceManager.GetString("SavedQueues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select destination directory.
        /// </summary>
        public static string SelectDestinationDirectory {
            get {
                return ResourceManager.GetString("SelectDestinationDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select music folder....
        /// </summary>
        public static string SelectMusicFolder {
            get {
                return ResourceManager.GetString("SelectMusicFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs.
        /// </summary>
        public static string Songs {
            get {
                return ResourceManager.GetString("Songs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs added to album.
        /// </summary>
        public static string SongsAddedToAlbum {
            get {
                return ResourceManager.GetString("SongsAddedToAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song volume.
        /// </summary>
        public static string SongVolume {
            get {
                return ResourceManager.GetString("SongVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound &amp;&amp; rating.
        /// </summary>
        public static string SoundRating {
            get {
                return ResourceManager.GetString("SoundRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string StarChar {
            get {
                return ResourceManager.GetString("StarChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stars.
        /// </summary>
        public static string Stars {
            get {
                return ResourceManager.GetString("Stars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test stuff.
        /// </summary>
        public static string TestStuff {
            get {
                return ResourceManager.GetString("TestStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time estimate (ready).
        /// </summary>
        public static string TimeEstimateReady {
            get {
                return ResourceManager.GetString("TimeEstimateReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total percentage (%).
        /// </summary>
        public static string TotalPercentage {
            get {
                return ResourceManager.GetString("TotalPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track.
        /// </summary>
        public static string Track {
            get {
                return ResourceManager.GetString("Track", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string Undo {
            get {
                return ResourceManager.GetString("Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Window.
        /// </summary>
        public static string Window {
            get {
                return ResourceManager.GetString("Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
