//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amp.Shared.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UiImageNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UiImageNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("amp.Shared.Localization.UiImageNames", typeof(UiImageNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add music files.
        /// </summary>
        public static string AddMusicFiles {
            get {
                return ResourceManager.GetString("AddMusicFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        public static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album lookup.
        /// </summary>
        public static string AlbumLookup {
            get {
                return ResourceManager.GetString("AlbumLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for new version.
        /// </summary>
        public static string CheckNewVersion {
            get {
                return ResourceManager.GetString("CheckNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear queue.
        /// </summary>
        public static string ClearQueue {
            get {
                return ResourceManager.GetString("ClearQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear search.
        /// </summary>
        public static string ClearSearch {
            get {
                return ResourceManager.GetString("ClearSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color settings.
        /// </summary>
        public static string ColorSettings {
            get {
                return ResourceManager.GetString("ColorSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help/About.
        /// </summary>
        public static string HelpAbout {
            get {
                return ResourceManager.GetString("HelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon settings.
        /// </summary>
        public static string IconSettings {
            get {
                return ResourceManager.GetString("IconSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main volume slider.
        /// </summary>
        public static string MainVolumeSlider {
            get {
                return ResourceManager.GetString("MainVolumeSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main volume slider speaker.
        /// </summary>
        public static string MainVolumeSliderSpeaker {
            get {
                return ResourceManager.GetString("MainVolumeSliderSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next track.
        /// </summary>
        public static string NextTrack {
            get {
                return ResourceManager.GetString("NextTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pop stashed queue.
        /// </summary>
        public static string PopStashedQueue {
            get {
                return ResourceManager.GetString("PopStashedQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position slider.
        /// </summary>
        public static string PositionSlider {
            get {
                return ResourceManager.GetString("PositionSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous track.
        /// </summary>
        public static string PreviousTrack {
            get {
                return ResourceManager.GetString("PreviousTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit application.
        /// </summary>
        public static string QuitApplication {
            get {
                return ResourceManager.GetString("QuitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist rating column.
        /// </summary>
        public static string RatingPlaylist {
            get {
                return ResourceManager.GetString("RatingPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlist rating column, undefined.
        /// </summary>
        public static string RatingPlaylistUndefined {
            get {
                return ResourceManager.GetString("RatingPlaylistUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating, undefined.
        /// </summary>
        public static string RatingUndefined {
            get {
                return ResourceManager.GetString("RatingUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save current queue.
        /// </summary>
        public static string SaveCurrentQueue {
            get {
                return ResourceManager.GetString("SaveCurrentQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved queues.
        /// </summary>
        public static string SavedQueues {
            get {
                return ResourceManager.GetString("SavedQueues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scramble queue.
        /// </summary>
        public static string ScrambleQueue {
            get {
                return ResourceManager.GetString("ScrambleQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show queue.
        /// </summary>
        public static string ShowQueue {
            get {
                return ResourceManager.GetString("ShowQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle.
        /// </summary>
        public static string Shuffle {
            get {
                return ResourceManager.GetString("Shuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack queue.
        /// </summary>
        public static string StackQueue {
            get {
                return ResourceManager.GetString("StackQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stash queue.
        /// </summary>
        public static string StashQueue {
            get {
                return ResourceManager.GetString("StashQueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track information.
        /// </summary>
        public static string TrackInformation {
            get {
                return ResourceManager.GetString("TrackInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track volume slider.
        /// </summary>
        public static string TrackVolumeSlider {
            get {
                return ResourceManager.GetString("TrackVolumeSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track volume slider speaker.
        /// </summary>
        public static string TrackVolumeSliderSpeaker {
            get {
                return ResourceManager.GetString("TrackVolumeSliderSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update track metadata.
        /// </summary>
        public static string UpdateTrackMetadata {
            get {
                return ResourceManager.GetString("UpdateTrackMetadata", resourceCulture);
            }
        }
    }
}
