site_name: amp help
site_url: ""
use_directory_urls: false
theme: 
  name: material
  language: fi

nav:
  - Tietoja: index.md
  - Asennus: install.md
  - Pääikkuna: main_window.md
  - Albumien hallinta: album.md
  - Kappaleen tiedot: track_info.md
  - Tallennetut jonot: saved_queues_dialog.md
  - Asetukset: settings.md
  - Värien asetukset: color_settings.md
  - Näppäinoikotiet: keyboard_shortcuts.md
  - Tiedon tallennus: data_storing.md
  - Lisenssi: license.md

copyright: Copyright &copy; 2022 VPKSoft