//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace amp.EtoForms.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("amp.EtoForms.Localization.UI", typeof(UI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string _ {
            get {
                return ResourceManager.GetString("_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add files....
        /// </summary>
        internal static string AddFiles {
            get {
                return ResourceManager.GetString("AddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add files to album....
        /// </summary>
        internal static string AddFilesToAlbum {
            get {
                return ResourceManager.GetString("AddFilesToAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add folder contents....
        /// </summary>
        internal static string AddFolderContents {
            get {
                return ResourceManager.GetString("AddFolderContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add folder contents to album....
        /// </summary>
        internal static string AddFolderContentsToAlbum {
            get {
                return ResourceManager.GetString("AddFolderContentsToAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add music....
        /// </summary>
        internal static string AddMusic {
            get {
                return ResourceManager.GetString("AddMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add music files....
        /// </summary>
        internal static string AddMusicFiles {
            get {
                return ResourceManager.GetString("AddMusicFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add music to album: &apos;{0}&apos;....
        /// </summary>
        internal static string AddMusicToAlbum0 {
            get {
                return ResourceManager.GetString("AddMusicToAlbum0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album entries.
        /// </summary>
        internal static string AlbumEntries {
            get {
                return ResourceManager.GetString("AlbumEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        internal static string Albums {
            get {
                return ResourceManager.GetString("Albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        internal static string ColonDelimiter {
            get {
                return ResourceManager.GetString("ColonDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database conversion.
        /// </summary>
        internal static string DatabaseConversion {
            get {
                return ResourceManager.GetString("DatabaseConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database updated.
        /// </summary>
        internal static string DatabaseUpdated {
            get {
                return ResourceManager.GetString("DatabaseUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directories searched.
        /// </summary>
        internal static string DirectoriesCrawled {
            get {
                return ResourceManager.GetString("DirectoriesCrawled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files found.
        /// </summary>
        internal static string FilesFound {
            get {
                return ResourceManager.GetString("FilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music files.
        /// </summary>
        internal static string MusicFiles {
            get {
                return ResourceManager.GetString("MusicFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} / {1}.
        /// </summary>
        internal static string NoOfNo {
            get {
                return ResourceManager.GetString("NoOfNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue entries.
        /// </summary>
        internal static string QueueEntries {
            get {
                return ResourceManager.GetString("QueueEntries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string Quit {
            get {
                return ResourceManager.GetString("Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select music folder....
        /// </summary>
        internal static string SelectMusicFolder {
            get {
                return ResourceManager.GetString("SelectMusicFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs.
        /// </summary>
        internal static string Songs {
            get {
                return ResourceManager.GetString("Songs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs added to album.
        /// </summary>
        internal static string SongsAddedToAlbum {
            get {
                return ResourceManager.GetString("SongsAddedToAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song volume.
        /// </summary>
        internal static string SongVolume {
            get {
                return ResourceManager.GetString("SongVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound &amp;&amp; rating.
        /// </summary>
        internal static string SoundRating {
            get {
                return ResourceManager.GetString("SoundRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stars.
        /// </summary>
        internal static string Stars {
            get {
                return ResourceManager.GetString("Stars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test stuff.
        /// </summary>
        internal static string TestStuff {
            get {
                return ResourceManager.GetString("TestStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time estimate (ready).
        /// </summary>
        internal static string TimeEstimateReady {
            get {
                return ResourceManager.GetString("TimeEstimateReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total percentage (%).
        /// </summary>
        internal static string TotalPercentage {
            get {
                return ResourceManager.GetString("TotalPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
    }
}
