name: .NET Core MacOS bundle

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore "$GITHUB_WORKSPACE/amp multiplatform.sln"
    - name: Dotnet publish    
      run: |
        mkdir -p "$GITHUB_WORKSPACE/Packaging/MacOS/bin"
        dotnet publish "$GITHUB_WORKSPACE/amp.EtoForms/amp.EtoForms.csproj" --configuration "Release" --output "$GITHUB_WORKSPACE/Packaging/MacOS/bin"
        mkdir -p "$GITHUB_WORKSPACE/Packaging/MacOS/amp.EtoForms.app/Contents/MacOS"
        mv "$GITHUB_WORKSPACE/Packaging/MacOS/bin/"* "$GITHUB_WORKSPACE/Packaging/MacOS/amp.EtoForms.app/Contents/MacOS"
