name: .NET Core Desktop Windows Installer

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/*.md'

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore "$Env:GITHUB_WORKSPACE/amp multiplatform.sln"
    - name: Publish
      run: dotnet publish --no-restore "$Env:GITHUB_WORKSPACE/amp.EtoForms/amp.EtoForms.csproj" --configuration Release

    - name: Create installer # Go give it a star(!): https://github.com/marketplace/actions/makensis
      uses: joncloud/makensis-action@v4.1
      with:
        arguments: "/V3"
        script-file: ${{ github.workspace }}/Packaging/Windows/setup_amp.nsi

    - uses: actions/upload-artifact@v4
      with:
        name: amp# installer
        path: ${{ github.workspace }}/Packaging/Windows/setup_amp.exe
        if-no-files-found: error
