name: .NET Core MacOS bundle

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore "$GITHUB_WORKSPACE/amp multiplatform.sln"
    - name: Dotnet publish    
      run: |
        cd "$GITHUB_WORKSPACE/Packaging/MacOS/"
        ./make_app.sh

    - uses: actions/upload-artifact@v4
      with:
        name: amp# application bundle
        path: ${{ github.workspace }}/Packaging/amp#.zip
