name: .NET Core MacOS bundle

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore "$GITHUB_WORKSPACE/amp multiplatform.sln"
    - name: Dotnet publish    
      run: |
        mkdir -p "$GITHUB_WORKSPACE/Packaging/MacOS/bin"
        dotnet publish "$GITHUB_WORKSPACE/amp.EtoForms/amp.EtoForms.csproj" --configuration "Release" --output "$GITHUB_WORKSPACE/Packaging/MacOS/bin"
        mkdir -p "$GITHUB_WORKSPACE/Packaging/MacOS/amp.EtoForms.app/Contents/MacOS"
        mv "$GITHUB_WORKSPACE/Packaging/MacOS/bin/"* "$GITHUB_WORKSPACE/Packaging/MacOS/amp.EtoForms.app/Contents/MacOS"
        mkdir -p "$GITHUB_WORKSPACE/Packaging/MacOS/amp.EtoForms.app/Contents/Resources"
        cp "$GITHUB_WORKSPACE/amp.EtoForms/Images/AmpIcon.icns" "$GITHUB_WORKSPACE/Packaging/MacOS/amp.EtoForms.app/Contents/Resources"
        cp "$GITHUB_WORKSPACE/Packaging/MacOS/Info.plist" "$GITHUB_WORKSPACE/Packaging/MacOS/amp.EtoForms.app/Contents"
        chmod +x "$GITHUB_WORKSPACE/Packaging/MacOS/amp.EtoForms.app/Contents/MacOS/amp.EtoForms"
        xattr -c "$GITHUB_WORKSPACE/Packaging/MacOS/amp.EtoForms.app/Contents/MacOS/amp.EtoForms"
        zip -r "$GITHUB_WORKSPACE/Packaging/MacOS/amp.EtoForms.app/" "$GITHUB_WORKSPACE/Packaking/amp.EtoForms.zip"

    - uses: actions/upload-artifact@v3
      with:
        name: amp# application bundle
        path: ${{ github.workspace }}/Packaging/amp.EtoForms.zip