name: MkDocs Help package

on:
  release:
    types: [published]
    branches: [ "master" ]   

jobs:
 help-release-linux:
    environment: BinRelease
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'      

      - name: Install MkDocs
        run: |
           pip install mkdocs
           pip install mkdocs-material
           cd "$GITHUB_WORKSPACE/Help"
           bash make_helps.sh
      
      - name: Release
        uses: softprops/action-gh-release@v2        
        with:
          files: ${{ github.workspace }}/Help/help_pack.zip
          token: ${{ secrets.RELEASE_TOKEN }}
