name: Linux, Windows and macOS .NET Core

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches: [ "master" ]    
    paths-ignore:
      - '**/README.md'

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore "$GITHUB_WORKSPACE/amp multiplatform.sln"
    - name: Build
      run: dotnet build --no-restore "$GITHUB_WORKSPACE/amp multiplatform.sln"
    - name: Test
      run: dotnet test --no-build --verbosity normal "$GITHUB_WORKSPACE/amp.Tests/amp.Tests.csproj"

  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore "$Env:GITHUB_WORKSPACE/amp multiplatform.sln"
    - name: Build
      run: dotnet build --no-restore "$Env:GITHUB_WORKSPACE/amp multiplatform.sln"
    - name: Test
      run: dotnet test --no-build --verbosity normal "$Env:GITHUB_WORKSPACE/amp.Tests/amp.Tests.csproj"

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore "$GITHUB_WORKSPACE/amp multiplatform.sln"
    - name: Build
      run: dotnet build --no-restore "$GITHUB_WORKSPACE/amp multiplatform.sln"
    - name: Test
      run: dotnet test --no-build --verbosity normal "$GITHUB_WORKSPACE/amp.Tests/amp.Tests.csproj"

