name: .NET Core Releases

on:
  release:
    types: [published]
    branches: [ "master" ]   

jobs:
 release-linux:
    environment: BinRelease
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x      
      - name: Restore dependencies
        run: dotnet restore "$GITHUB_WORKSPACE/amp multiplatform.sln"          
      - name: Dotnet publish
        run: |
          cd "$GITHUB_WORKSPACE/Packaging/Linux/AppImage"
          ./release.sh
      - name: Release
        uses: softprops/action-gh-release@v1        
        with:
          files: ${{ github.workspace }}/Packaging/Linux/AppImage/amp#-x86_64.AppImage
          token: ${{ secrets.RELEASE_TOKEN }}

 release-macos:
  environment: BinRelease
  runs-on: macos-latest

  steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore "$GITHUB_WORKSPACE/amp multiplatform.sln"
    - name: Dotnet publish    
      run: |
        mkdir -p "$GITHUB_WORKSPACE/Packaging/MacOS/bin"
        dotnet publish "$GITHUB_WORKSPACE/amp.EtoForms/amp.EtoForms.csproj" --configuration "Release" --output "$GITHUB_WORKSPACE/Packaging/MacOS/bin"
        mkdir -p "$GITHUB_WORKSPACE/Packaging/MacOS/amp.EtoForms.app/Contents/MacOS"
        mv "$GITHUB_WORKSPACE/Packaging/MacOS/bin/"* "$GITHUB_WORKSPACE/Packaging/MacOS/amp.EtoForms.app/Contents/MacOS"
        mkdir -p "$GITHUB_WORKSPACE/Packaging/MacOS/amp.EtoForms.app/Contents/Resources"
        cp "$GITHUB_WORKSPACE/amp.EtoForms/Images/AmpIcon.icns" "$GITHUB_WORKSPACE/Packaging/MacOS/amp.EtoForms.app/Contents/Resources"
        cp "$GITHUB_WORKSPACE/Packaging/MacOS/Info.plist" "$GITHUB_WORKSPACE/Packaging/MacOS/amp.EtoForms.app/Contents"
        chmod +x "$GITHUB_WORKSPACE/Packaging/MacOS/amp.EtoForms.app/Contents/MacOS/amp.EtoForms"
        xattr -c "$GITHUB_WORKSPACE/Packaging/MacOS/amp.EtoForms.app/Contents/MacOS/amp.EtoForms"
        chmod +x "$GITHUB_WORKSPACE/Packaging/MacOS/amp.EtoForms.app"
        xattr -c "$GITHUB_WORKSPACE/Packaging/MacOS/amp.EtoForms.app"
        cd "$GITHUB_WORKSPACE/Packaging/MacOS/"
        zip -r "$GITHUB_WORKSPACE/Packaging/amp.EtoForms.zip" amp.EtoForms.app
        
    - name: Release
      uses: softprops/action-gh-release@v1        
      with:
        files: ${{ github.workspace }}/Packaging/amp.EtoForms.zip
        token: ${{ secrets.RELEASE_TOKEN }}

 release-windows:
  environment: BinRelease
  runs-on: windows-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore "$Env:GITHUB_WORKSPACE/amp multiplatform.sln"
    - name: Publish
      run: dotnet publish --no-restore "$Env:GITHUB_WORKSPACE/amp.EtoForms/amp.EtoForms.csproj" --configuration Release
    - name: Create installer # Go give it a star(!): https://github.com/marketplace/actions/makensis
      uses: joncloud/makensis-action@v3.7
      with:
        arguments: "/V3"
        script-file: ${{ github.workspace }}/Packaging/Windows/setup_amp#.nsi
    - name: Release
      uses: softprops/action-gh-release@v1        
      with:
        files: ${{ github.workspace }}/Packaging/Windows/setup_amp#.exe
        token: ${{ secrets.RELEASE_TOKEN }}        
