name: .NET Core Releases

on:
  release:
    types: [published]
    branches: [ "master" ]   

jobs:
 release-linux:
    environment: BinRelease
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x      
      - name: Restore dependencies
        run: dotnet restore "$GITHUB_WORKSPACE/amp multiplatform.sln"          
      - name: Install LibFuse2
        run: |
          sudo add-apt-repository universe
          sudo apt install libfuse2        
      - name: Dotnet publish
        run: |
          cd "$GITHUB_WORKSPACE/Packaging/Linux/AppImage"
          ./release.sh
      - name: Release
        uses: softprops/action-gh-release@v2        
        with:
          files: ${{ github.workspace }}/Packaging/Linux/AppImage/amp#-x86_64.AppImage
          token: ${{ secrets.RELEASE_TOKEN }}

 release-macos:
  environment: BinRelease
  runs-on: macos-latest

  steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore "$GITHUB_WORKSPACE/amp multiplatform.sln"
    - name: Dotnet publish    
      run: |
        cd "$GITHUB_WORKSPACE/Packaging/MacOS/"
        ./make_app.sh
        
    - name: Release
      uses: softprops/action-gh-release@v2        
      with:
        files: ${{ github.workspace }}/Packaging/amp#.zip
        token: ${{ secrets.RELEASE_TOKEN }}

 release-windows:
  environment: BinRelease
  runs-on: windows-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore "$Env:GITHUB_WORKSPACE/amp multiplatform.sln"
    - name: Publish
      run: dotnet publish --no-restore "$Env:GITHUB_WORKSPACE/amp.EtoForms/amp.EtoForms.csproj" --configuration Release
    - name: Create installer # Go give it a star(!): https://github.com/marketplace/actions/makensis
      uses: joncloud/makensis-action@v4.1
      with:
        arguments: "/V3"
        script-file: ${{ github.workspace }}/Packaging/Windows/setup_amp.nsi
    - name: Release
      uses: softprops/action-gh-release@v2        
      with:
        files: ./Packaging/Windows/setup_amp.exe
        token: ${{ secrets.RELEASE_TOKEN }}
